require "active_admin_menu/allocator"
require "active_admin_menu/config"
require "active_admin_menu/dsl"
require "active_admin_menu/item"
require "active_admin_menu/menu"
require "active_admin_menu/railtie"
require "active_admin_menu/version"
